/*
 * mnemonics.c
 *
 *  Created on: 11/01/2011
 *      Author: viniciusrodrigues
 */

#include "mnemonics.h"

opcode_info* get_opcode_info() {
	int i;

	op_info = (opcode_info*)malloc(sizeof(opcode_info)*255);

	strcpy(op_info[0x32].mnemonic, "aaload");
	strcpy(op_info[0x53].mnemonic, "aastore");
	strcpy(op_info[0x01].mnemonic, "aconst_null");
	strcpy(op_info[0x19].mnemonic, "aload");
	strcpy(op_info[0x2a].mnemonic, "aload_0");
	strcpy(op_info[0x2b].mnemonic, "aload_1");
	strcpy(op_info[0x2c].mnemonic, "aload_2");
	strcpy(op_info[0x2d].mnemonic, "aload_3");
	strcpy(op_info[0xbd].mnemonic, "anewarray");
	strcpy(op_info[0xb0].mnemonic, "areturn");
	strcpy(op_info[0xbe].mnemonic, "arraylength");
	strcpy(op_info[0x3a].mnemonic, "astore");
	strcpy(op_info[0x4b].mnemonic, "astore_0");
	strcpy(op_info[0x4c].mnemonic, "astore_1");
	strcpy(op_info[0x4d].mnemonic, "astore_2");
	strcpy(op_info[0x4e].mnemonic, "astore_3");
	strcpy(op_info[0xbf].mnemonic, "athrow");
	strcpy(op_info[0x33].mnemonic, "baload");
	strcpy(op_info[0x54].mnemonic, "bastore");
	strcpy(op_info[0x10].mnemonic, "bipush");
	strcpy(op_info[0x34].mnemonic, "caload");
	strcpy(op_info[0x55].mnemonic, "castore");
	strcpy(op_info[0xc0].mnemonic, "checkcast");
	strcpy(op_info[0x90].mnemonic, "d2f");
	strcpy(op_info[0x8e].mnemonic, "d2i");
	strcpy(op_info[0x8f].mnemonic, "d2l");
	strcpy(op_info[0x63].mnemonic, "dadd");
	strcpy(op_info[0x31].mnemonic, "daload");
	strcpy(op_info[0x52].mnemonic, "dastore");
	strcpy(op_info[0x98].mnemonic, "dcmpg");
	strcpy(op_info[0x97].mnemonic, "dcmpl");
	strcpy(op_info[0x0e].mnemonic, "dconst_0");
	strcpy(op_info[0x0f].mnemonic, "dconst_1");
	strcpy(op_info[0x6f].mnemonic, "ddiv");
	strcpy(op_info[0x18].mnemonic, "dload");
	strcpy(op_info[0x26].mnemonic, "dload_0");
	strcpy(op_info[0x27].mnemonic, "dload_1");
	strcpy(op_info[0x28].mnemonic, "dload_2");
	strcpy(op_info[0x29].mnemonic, "dload_3");
	strcpy(op_info[0x6b].mnemonic, "dmul");
	strcpy(op_info[0x77].mnemonic, "dneg");
	strcpy(op_info[0x73].mnemonic, "drem");
	strcpy(op_info[0xaf].mnemonic, "dreturn");
	strcpy(op_info[0x39].mnemonic, "dstore");
	strcpy(op_info[0x47].mnemonic, "dstore_0");
	strcpy(op_info[0x48].mnemonic, "dstore_1");
	strcpy(op_info[0x49].mnemonic, "dstore_2");
	strcpy(op_info[0x4a].mnemonic, "dstore_3");
	strcpy(op_info[0x67].mnemonic, "dsub");
	strcpy(op_info[0x59].mnemonic, "dup");
	strcpy(op_info[0x5a].mnemonic, "dup_x1");
	strcpy(op_info[0x5b].mnemonic, "dup_x2");
	strcpy(op_info[0x5c].mnemonic, "dup2");
	strcpy(op_info[0x5d].mnemonic, "dup2_x1");
	strcpy(op_info[0x5e].mnemonic, "dup2_x2");
	strcpy(op_info[0x8d].mnemonic, "f2d");
	strcpy(op_info[0x8b].mnemonic, "f2i");
	strcpy(op_info[0x8c].mnemonic, "f2l");
	strcpy(op_info[0x62].mnemonic, "fadd");
	strcpy(op_info[0x30].mnemonic, "faload");
	strcpy(op_info[0x51].mnemonic, "fastore");
	strcpy(op_info[0x96].mnemonic, "fcmpg");
	strcpy(op_info[0x95].mnemonic, "fcmpl");
	strcpy(op_info[0x0b].mnemonic, "fconst_0");
	strcpy(op_info[0x0c].mnemonic, "fconst_1");
	strcpy(op_info[0x0d].mnemonic, "fconst_2");
	strcpy(op_info[0x6e].mnemonic, "fdiv");
	strcpy(op_info[0x17].mnemonic, "fload");
	strcpy(op_info[0x22].mnemonic, "fload_0");
	strcpy(op_info[0x23].mnemonic, "fload_1");
	strcpy(op_info[0x24].mnemonic, "fload_2");
	strcpy(op_info[0x25].mnemonic, "fload_3");
	strcpy(op_info[0x6a].mnemonic, "fmul");
	strcpy(op_info[0x76].mnemonic, "fneg");
	strcpy(op_info[0x72].mnemonic, "frem");
	strcpy(op_info[0xae].mnemonic, "freturn");
	strcpy(op_info[0x38].mnemonic, "fstore");
	strcpy(op_info[0x43].mnemonic, "fstore_0");
	strcpy(op_info[0x44].mnemonic, "fstore_1");
	strcpy(op_info[0x45].mnemonic, "fstore_2");
	strcpy(op_info[0x46].mnemonic, "fstore_3");
	strcpy(op_info[0x66].mnemonic, "fsub");
	strcpy(op_info[0xb4].mnemonic, "getfield");
	strcpy(op_info[0xb2].mnemonic, "getstatic");
	strcpy(op_info[0xa7].mnemonic, "goto");
	strcpy(op_info[0xc8].mnemonic, "goto_w");
	strcpy(op_info[0x91].mnemonic, "i2b");
	strcpy(op_info[0x92].mnemonic, "i2c");
	strcpy(op_info[0x87].mnemonic, "i2d");
	strcpy(op_info[0x86].mnemonic, "i2f");
	strcpy(op_info[0x85].mnemonic, "i2l");
	strcpy(op_info[0x93].mnemonic, "i2s");
	strcpy(op_info[0x60].mnemonic, "iadd");
	strcpy(op_info[0x2e].mnemonic, "iaload");
	strcpy(op_info[0x7e].mnemonic, "iand");
	strcpy(op_info[0x4f].mnemonic, "iastore");
	strcpy(op_info[0x02].mnemonic, "iconst_m1");
	strcpy(op_info[0x03].mnemonic, "iconst_0");
	strcpy(op_info[0x04].mnemonic, "iconst_1");
	strcpy(op_info[0x05].mnemonic, "iconst_2");
	strcpy(op_info[0x06].mnemonic, "iconst_3");
	strcpy(op_info[0x07].mnemonic, "iconst_4");
	strcpy(op_info[0x08].mnemonic, "iconst_5");
	strcpy(op_info[0x6c].mnemonic, "idiv");
	strcpy(op_info[0xa5].mnemonic, "if_acmpeq");
	strcpy(op_info[0xa6].mnemonic, "if_acmpne");
	strcpy(op_info[0x9f].mnemonic, "if_icmpeq");
	strcpy(op_info[0xa0].mnemonic, "if_icmpne");
	strcpy(op_info[0xa1].mnemonic, "if_icmplt");
	strcpy(op_info[0xa2].mnemonic, "if_icmpge");
	strcpy(op_info[0xa3].mnemonic, "if_icmpgt");
	strcpy(op_info[0xa4].mnemonic, "if_icmple");
	strcpy(op_info[0x99].mnemonic, "ifeq");
	strcpy(op_info[0x9a].mnemonic, "ifne");
	strcpy(op_info[0x9b].mnemonic, "iflt");
	strcpy(op_info[0x9c].mnemonic, "ifge");
	strcpy(op_info[0x9d].mnemonic, "ifgt");
	strcpy(op_info[0x9e].mnemonic, "ifle");
	strcpy(op_info[0xc7].mnemonic, "ifnonnull");
	strcpy(op_info[0xc6].mnemonic, "ifnull");
	strcpy(op_info[0x84].mnemonic, "iinc");
	strcpy(op_info[0x15].mnemonic, "iload");
	strcpy(op_info[0x1a].mnemonic, "iload_0");
	strcpy(op_info[0x1b].mnemonic, "iload_1");
	strcpy(op_info[0x1c].mnemonic, "iload_2");
	strcpy(op_info[0x1d].mnemonic, "iload_3");
	strcpy(op_info[0x68].mnemonic, "imul");
	strcpy(op_info[0x74].mnemonic, "ineg");
	strcpy(op_info[0xc1].mnemonic, "instanceof");
	strcpy(op_info[0xb9].mnemonic, "invokeinterface");
	strcpy(op_info[0xb7].mnemonic, "invokespecial");
	strcpy(op_info[0xb8].mnemonic, "invokestatic");
	strcpy(op_info[0xb6].mnemonic, "invokevirtual");
	strcpy(op_info[0x80].mnemonic, "ior");
	strcpy(op_info[0x70].mnemonic, "irem");
	strcpy(op_info[0xac].mnemonic, "ireturn");
	strcpy(op_info[0x78].mnemonic, "ishl");
	strcpy(op_info[0x7a].mnemonic, "ishr");
	strcpy(op_info[0x36].mnemonic, "istore");
	strcpy(op_info[0x3b].mnemonic, "istore_0");
	strcpy(op_info[0x3c].mnemonic, "istore_1");
	strcpy(op_info[0x3d].mnemonic, "istore_2");
	strcpy(op_info[0x3e].mnemonic, "istore_3");
	strcpy(op_info[0x64].mnemonic, "isub");
	strcpy(op_info[0x7c].mnemonic, "iushr");
	strcpy(op_info[0x82].mnemonic, "ixor");
	strcpy(op_info[0xa8].mnemonic, "jsr");
	strcpy(op_info[0xc9].mnemonic, "jsr_w");
	strcpy(op_info[0x8a].mnemonic, "l2d");
	strcpy(op_info[0x89].mnemonic, "l2f");
	strcpy(op_info[0x88].mnemonic, "l2i");
	strcpy(op_info[0x61].mnemonic, "ladd");
	strcpy(op_info[0x2f].mnemonic, "laload");
	strcpy(op_info[0x7f].mnemonic, "land");
	strcpy(op_info[0x50].mnemonic, "lastore");
	strcpy(op_info[0x94].mnemonic, "lcmp");
	strcpy(op_info[0x09].mnemonic, "lconst_0");
	strcpy(op_info[0x0a].mnemonic, "lconst_1");
	strcpy(op_info[0x12].mnemonic, "ldc");
	strcpy(op_info[0x13].mnemonic, "ldc_w");
	strcpy(op_info[0x14].mnemonic, "ldc2_w");
	strcpy(op_info[0x6d].mnemonic, "ldiv");
	strcpy(op_info[0x16].mnemonic, "lload");
	strcpy(op_info[0x1e].mnemonic, "lload_0");
	strcpy(op_info[0x1f].mnemonic, "lload_1");
	strcpy(op_info[0x20].mnemonic, "lload_2");
	strcpy(op_info[0x21].mnemonic, "lload_3");
	strcpy(op_info[0x69].mnemonic, "lmul");
	strcpy(op_info[0x75].mnemonic, "lneg");
	strcpy(op_info[0xab].mnemonic, "lookupswitch");
	strcpy(op_info[0x81].mnemonic, "lor");
	strcpy(op_info[0x71].mnemonic, "lrem");
	strcpy(op_info[0xad].mnemonic, "lreturn");
	strcpy(op_info[0x79].mnemonic, "lshl");
	strcpy(op_info[0x7b].mnemonic, "lshr");
	strcpy(op_info[0x37].mnemonic, "lstore");
	strcpy(op_info[0x3f].mnemonic, "lstore_0");
	strcpy(op_info[0x40].mnemonic, "lstore_1");
	strcpy(op_info[0x41].mnemonic, "lstore_2");
	strcpy(op_info[0x42].mnemonic, "lstore_3");
	strcpy(op_info[0x65].mnemonic, "lsub");
	strcpy(op_info[0x7d].mnemonic, "lushr");
	strcpy(op_info[0x83].mnemonic, "lxor");
	strcpy(op_info[0xc2].mnemonic, "monitorenter");
	strcpy(op_info[0xc3].mnemonic, "monitorexit");
	strcpy(op_info[0xc5].mnemonic, "multianewarray");
	strcpy(op_info[0xbb].mnemonic, "new");
	strcpy(op_info[0xbc].mnemonic, "newarray");
	strcpy(op_info[0x00].mnemonic, "nop");
	strcpy(op_info[0x57].mnemonic, "pop");
	strcpy(op_info[0x58].mnemonic, "pop2");
	strcpy(op_info[0xb5].mnemonic, "putfield");
	strcpy(op_info[0xb3].mnemonic, "putstatic");
	strcpy(op_info[0xa9].mnemonic, "ret");
	strcpy(op_info[0xb1].mnemonic, "return");
	strcpy(op_info[0x35].mnemonic, "saload");
	strcpy(op_info[0x56].mnemonic, "sastore");
	strcpy(op_info[0x11].mnemonic, "sipush");
	strcpy(op_info[0x5f].mnemonic, "swap");
	strcpy(op_info[0xaa].mnemonic, "tableswitch");
	strcpy(op_info[0xc4].mnemonic, "wide");
	strcpy(op_info[0xca].mnemonic, "breakpoint");
	strcpy(op_info[0xfe].mnemonic, "impdep1");
	strcpy(op_info[0xff].mnemonic, "impdep2");
	strcpy(op_info[0xba].mnemonic, "xxxunusedxxx");

	for (i = 0xcb; i < 0xfe; i++) {
		strcpy(op_info[i].mnemonic, "(no name)");
	}


	op_info[0x32].operands_count = 0;
	op_info[0x53].operands_count = 0;
	op_info[0x01].operands_count = 0;
	op_info[0x19].operands_count = 1;
	op_info[0x2a].operands_count = 0;
	op_info[0x2b].operands_count = 0;
	op_info[0x2c].operands_count = 0;
	op_info[0x2d].operands_count = 0;
	op_info[0xbd].operands_count = 2;
	op_info[0xb0].operands_count = 0;
	op_info[0xbe].operands_count = 0;
	op_info[0x3a].operands_count = 1;
	op_info[0x4b].operands_count = 0;
	op_info[0x4c].operands_count = 0;
	op_info[0x4d].operands_count = 0;
	op_info[0x4e].operands_count = 0;
	op_info[0xbf].operands_count = 0;
	op_info[0x33].operands_count = 0;
	op_info[0x54].operands_count = 0;
	op_info[0x10].operands_count = 1;
	op_info[0x34].operands_count = 0;
	op_info[0x55].operands_count = 0;
	op_info[0xc0].operands_count = 2;
	op_info[0x90].operands_count = 0;
	op_info[0x8e].operands_count = 0;
	op_info[0x8f].operands_count = 0;
	op_info[0x63].operands_count = 0;
	op_info[0x31].operands_count = 0;
	op_info[0x52].operands_count = 0;
	op_info[0x98].operands_count = 0;
	op_info[0x97].operands_count = 0;
	op_info[0x0e].operands_count = 0;
	op_info[0x0f].operands_count = 0;
	op_info[0x6f].operands_count = 0;
	op_info[0x18].operands_count = 1;
	op_info[0x26].operands_count = 0;
	op_info[0x27].operands_count = 0;
	op_info[0x28].operands_count = 0;
	op_info[0x29].operands_count = 0;
	op_info[0x6b].operands_count = 0;
	op_info[0x77].operands_count = 0;
	op_info[0x73].operands_count = 0;
	op_info[0xaf].operands_count = 0;
	op_info[0x39].operands_count = 1;
	op_info[0x47].operands_count = 0;
	op_info[0x48].operands_count = 0;
	op_info[0x49].operands_count = 0;
	op_info[0x4a].operands_count = 0;
	op_info[0x67].operands_count = 0;
	op_info[0x59].operands_count = 0;
	op_info[0x5a].operands_count = 0;
	op_info[0x5b].operands_count = 0;
	op_info[0x5c].operands_count = 0;
	op_info[0x5d].operands_count = 0;
	op_info[0x5e].operands_count = 0;
	op_info[0x8d].operands_count = 0;
	op_info[0x8b].operands_count = 0;
	op_info[0x8c].operands_count = 0;
	op_info[0x62].operands_count = 0;
	op_info[0x30].operands_count = 0;
	op_info[0x51].operands_count = 0;
	op_info[0x96].operands_count = 0;
	op_info[0x95].operands_count = 0;
	op_info[0x0b].operands_count = 0;
	op_info[0x0c].operands_count = 0;
	op_info[0x0d].operands_count = 0;
	op_info[0x6e].operands_count = 0;
	op_info[0x17].operands_count = 1;
	op_info[0x22].operands_count = 0;
	op_info[0x23].operands_count = 0;
	op_info[0x24].operands_count = 0;
	op_info[0x25].operands_count = 0;
	op_info[0x6a].operands_count = 0;
	op_info[0x76].operands_count = 0;
	op_info[0x72].operands_count = 0;
	op_info[0xae].operands_count = 0;
	op_info[0x38].operands_count = 1;
	op_info[0x43].operands_count = 0;
	op_info[0x44].operands_count = 0;
	op_info[0x45].operands_count = 0;
	op_info[0x46].operands_count = 0;
	op_info[0x66].operands_count = 0;
	op_info[0xb4].operands_count = 2;
	op_info[0xb2].operands_count = 2;
	op_info[0xa7].operands_count = 2;
	op_info[0xc8].operands_count = 4;
	op_info[0x91].operands_count = 0;
	op_info[0x92].operands_count = 0;
	op_info[0x87].operands_count = 0;
	op_info[0x86].operands_count = 0;
	op_info[0x85].operands_count = 0;
	op_info[0x93].operands_count = 0;
	op_info[0x60].operands_count = 0;
	op_info[0x2e].operands_count = 0;
	op_info[0x7e].operands_count = 0;
	op_info[0x4f].operands_count = 0;
	op_info[0x02].operands_count = 0;
	op_info[0x03].operands_count = 0;
	op_info[0x04].operands_count = 0;
	op_info[0x05].operands_count = 0;
	op_info[0x06].operands_count = 0;
	op_info[0x07].operands_count = 0;
	op_info[0x08].operands_count = 0;
	op_info[0x6c].operands_count = 0;
	op_info[0xa5].operands_count = 2;
	op_info[0xa6].operands_count = 2;
	op_info[0x9f].operands_count = 2;
	op_info[0xa0].operands_count = 2;
	op_info[0xa1].operands_count = 2;
	op_info[0xa2].operands_count = 2;
	op_info[0xa3].operands_count = 2;
	op_info[0xa4].operands_count = 2;
	op_info[0x99].operands_count = 2;
	op_info[0x9a].operands_count = 2;
	op_info[0x9b].operands_count = 2;
	op_info[0x9c].operands_count = 2;
	op_info[0x9d].operands_count = 2;
	op_info[0x9e].operands_count = 2;
	op_info[0xc7].operands_count = 2;
	op_info[0xc6].operands_count = 2;
	op_info[0x84].operands_count = 2;
	op_info[0x15].operands_count = 1;
	op_info[0x1a].operands_count = 0;
	op_info[0x1b].operands_count = 0;
	op_info[0x1c].operands_count = 0;
	op_info[0x1d].operands_count = 0;
	op_info[0x68].operands_count = 0;
	op_info[0x74].operands_count = 0;
	op_info[0xc1].operands_count = 2;
	op_info[0xb9].operands_count = 2;
	op_info[0xb7].operands_count = 2;
	op_info[0xb8].operands_count = 2;
	op_info[0xb6].operands_count = 2;
	op_info[0x80].operands_count = 0;
	op_info[0x70].operands_count = 0;
	op_info[0xac].operands_count = 0;
	op_info[0x78].operands_count = 0;
	op_info[0x7a].operands_count = 0;
	op_info[0x36].operands_count = 1;
	op_info[0x3b].operands_count = 0;
	op_info[0x3c].operands_count = 0;
	op_info[0x3d].operands_count = 0;
	op_info[0x3e].operands_count = 0;
	op_info[0x64].operands_count = 0;
	op_info[0x7c].operands_count = 0;
	op_info[0x82].operands_count = 0;
	op_info[0xa8].operands_count = 2;
	op_info[0xc9].operands_count = 4;
	op_info[0x8a].operands_count = 0;
	op_info[0x89].operands_count = 0;
	op_info[0x88].operands_count = 0;
	op_info[0x61].operands_count = 0;
	op_info[0x2f].operands_count = 0;
	op_info[0x7f].operands_count = 0;
	op_info[0x50].operands_count = 0;
	op_info[0x94].operands_count = 0;
	op_info[0x09].operands_count = 0;
	op_info[0x0a].operands_count = 0;
	op_info[0x12].operands_count = 1;
	op_info[0x13].operands_count = 2;
	op_info[0x14].operands_count = 2;
	op_info[0x6d].operands_count = 0;
	op_info[0x16].operands_count = 1;
	op_info[0x1e].operands_count = 0;
	op_info[0x1f].operands_count = 0;
	op_info[0x20].operands_count = 0;
	op_info[0x21].operands_count = 0;
	op_info[0x69].operands_count = 0;
	op_info[0x75].operands_count = 0;
	op_info[0xab].operands_count = 0;
	op_info[0x81].operands_count = 0;
	op_info[0x71].operands_count = 0;
	op_info[0xad].operands_count = 0;
	op_info[0x79].operands_count = 0;
	op_info[0x7b].operands_count = 0;
	op_info[0x37].operands_count = 1;
	op_info[0x3f].operands_count = 0;
	op_info[0x40].operands_count = 0;
	op_info[0x41].operands_count = 0;
	op_info[0x42].operands_count = 0;
	op_info[0x65].operands_count = 0;
	op_info[0x7d].operands_count = 0;
	op_info[0x83].operands_count = 0;
	op_info[0xc2].operands_count = 0;
	op_info[0xc3].operands_count = 0;
	op_info[0xc5].operands_count = 3;
	op_info[0xbb].operands_count = 2;
	op_info[0xbc].operands_count = 1;
	op_info[0x00].operands_count = 0;
	op_info[0x57].operands_count = 0;
	op_info[0x58].operands_count = 0;
	op_info[0xb5].operands_count = 2;
	op_info[0xb3].operands_count = 2;
	op_info[0xa9].operands_count = 1;
	op_info[0xb1].operands_count = 0;
	op_info[0x35].operands_count = 0;
	op_info[0x56].operands_count = 0;
	op_info[0x11].operands_count = 2;
	op_info[0x5f].operands_count = 0;
	op_info[0xaa].operands_count = 0;
	op_info[0xc4].operands_count = 7;
	op_info[0xca].operands_count = 0;
	op_info[0xfe].operands_count = 0;
	op_info[0xff].operands_count = 0;
	op_info[0xba].operands_count = 0;

	for (i = 0xcb; i < 0xfe; i++) {
		op_info[i].operands_count = 0;
	}

	return op_info;
}

