# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = classViewer/classViewer.o engine/executeEngine.o engine/executeInstructions.o engine/instructions.o reader/classFileReader.o reader/classLoader.o reader/attribute/attributeUtil.o structures/frame.o structures/heap.o structures/methodArea.o structures/mnemonics.o main.o $(RES)
LINKOBJ  = classViewer/classViewer.o engine/executeEngine.o engine/executeInstructions.o engine/instructions.o reader/classFileReader.o reader/classLoader.o reader/attribute/attributeUtil.o structures/frame.o structures/heap.o structures/methodArea.o structures/mnemonics.o main.o $(RES)
LIBS =  -L"C:/MinGW/lib"  
INCS =  -I"C:/MinGW/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = jvm-project.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before jvm-project.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "jvm-project.exe" $(LIBS)

classViewer/classViewer.o: classViewer/classViewer.c
	$(CC) -c classViewer/classViewer.c -o classViewer/classViewer.o $(CFLAGS)

engine/executeEngine.o: engine/executeEngine.c
	$(CC) -c engine/executeEngine.c -o engine/executeEngine.o $(CFLAGS)

engine/executeInstructions.o: engine/executeInstructions.c
	$(CC) -c engine/executeInstructions.c -o engine/executeInstructions.o $(CFLAGS)

engine/instructions.o: engine/instructions.c
	$(CC) -c engine/instructions.c -o engine/instructions.o $(CFLAGS)

reader/classFileReader.o: reader/classFileReader.c
	$(CC) -c reader/classFileReader.c -o reader/classFileReader.o $(CFLAGS)

reader/classLoader.o: reader/classLoader.c
	$(CC) -c reader/classLoader.c -o reader/classLoader.o $(CFLAGS)

reader/attribute/attributeUtil.o: reader/attribute/attributeUtil.c
	$(CC) -c reader/attribute/attributeUtil.c -o reader/attribute/attributeUtil.o $(CFLAGS)

structures/frame.o: structures/frame.c
	$(CC) -c structures/frame.c -o structures/frame.o $(CFLAGS)

structures/heap.o: structures/heap.c
	$(CC) -c structures/heap.c -o structures/heap.o $(CFLAGS)

structures/methodArea.o: structures/methodArea.c
	$(CC) -c structures/methodArea.c -o structures/methodArea.o $(CFLAGS)

structures/mnemonics.o: structures/mnemonics.c
	$(CC) -c structures/mnemonics.c -o structures/mnemonics.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
